# Generated by Django 3.2 on 2023-02-21 21:40

import apps.utils.directory_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(db_column='IdCompany', primary_key=True, serialize=False)),
                ('company_name', models.TextField(db_column='CompanyName')),
                ('logo', models.FileField(blank=True, db_column='Logo', null=True, upload_to=apps.utils.directory_path.logo_path)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.AutoField(db_column='IdDepartment', primary_key=True, serialize=False)),
                ('link_name', models.CharField(blank=True, db_column='Name', max_length=150, null=True)),
                ('generated_link', models.CharField(blank=True, db_column='GeneratedLink', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, db_column='Comment', null=True)),
                ('attachment', models.FileField(blank=True, db_column='Attachment', null=True, upload_to=apps.utils.directory_path.file_path)),
            ],
            options={
                'db_table': 'LinkInfo',
            },
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.AutoField(db_column='IdProcessStatus', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=150, null=True)),
            ],
            options={
                'db_table': 'ProcessStatus',
            },
        ),
        migrations.CreateModel(
            name='ProcessSteps',
            fields=[
                ('id', models.AutoField(db_column='IdProcessExtra', primary_key=True, serialize=False)),
                ('step_name', models.TextField(db_column='StepName')),
                ('register_date', models.DateField(auto_now_add=True, db_column='RegisterDate')),
                ('calendar_date', models.DateField(blank=True, db_column='CalendarDate', null=True)),
                ('register_date_time', models.DateTimeField(blank=True, db_column='RegisterDateTime', null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('hours', models.IntegerField(blank=True, default=0, null=True)),
                ('am_pm', models.TextField(blank=True, db_column='AMPM', null=True)),
                ('link_info', models.ForeignKey(db_column='IdLinkInfo', on_delete=django.db.models.deletion.CASCADE, to='administrators.linkinfo')),
                ('process_status', models.ForeignKey(db_column='ProcessStatus', on_delete=django.db.models.deletion.CASCADE, to='administrators.processstatus')),
            ],
            options={
                'db_table': 'ProcessSteps',
            },
        ),
    ]
