# Generated by Django 3.2 on 2023-02-17 21:23

import apps.utils.directory_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_processsteps_register_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(db_column='IdCompany', primary_key=True, serialize=False)),
                ('company_name', models.TextField(db_column='CompanyName')),
                ('logo', models.FileField(blank=True, db_column='Logo', null=True, upload_to=apps.utils.directory_path.file_path)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
