# Generated by Django 3.2 on 2023-02-21 17:55

import apps.utils.directory_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsteps',
            name='am_pm',
            field=models.TextField(blank=True, db_column='AMPM', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, db_column='Logo', null=True, upload_to=apps.utils.directory_path.logo_path),
        ),
    ]
